# Generated by Django 4.2.2 on 2024-11-05 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0003_alter_mailing_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'permissions': [('can_edit_status', 'Can edit status'), ('can_view_mailing', 'Can view mailing'), ('can_view_user', 'Can view user')], 'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
    ]
