# Generated by Django 4.2.2 on 2024-11-05 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Содержимое статьи')),
                ('image', models.ImageField(blank=True, help_text='Загрузите изображение', null=True, upload_to='images/', verbose_name='Превью')),
                ('views_count', models.IntegerField(default=0, verbose_name='количество просмотров')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'ordering': ['title', '-created_at'],
            },
        ),
    ]
